name: action test

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: thomasjungblut/twitter-action@v2
        with:
          message: "actual tweet test from actions"  
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }} 
