name: AnnounceBlogPost
on:
  page_build # TODO maybe should run at deploy time?
    
jobs:	
  tweet:	
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.event}}"      
#      - uses: actions/checkout@v2
#      - uses: thomasjungblut/twitter-action@v3
#        with:	
#          message: "tweeting from ${{ github.event.inputs.name }}"
#          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}	
#          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}	
#          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}	
#          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }} 
